### ISSUE TITLE
Running cpan install on Darwin

### ISSUE THREAD

**Issue by Levelleor** [ccin2p3/puppet-cpan#62]
I understand that the module isn't meant to be supported on Mac but I think the issue should be the same for Linux:

`perl -MCPAN -e 'CPAN::Shell->force(qw(install ${package}))'`

This command would not work when run via Puppet. Do you know by any chance why is it trying to create a CPAN directory in the root space?

` mkdir /CPAN: Read-only file system at /usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/CPAN/HandleConfig.pm line 601.`

I don't seem to be able to find any manuals of required environment variables required by CPAN to run properly, while it is surely missing something to install those modules to a specific directory.

**Comment by theevilapplepie** [comment]
This looks like this is caused by your cpan_home being set to /

The following config parameters need to be reset to resolve ( or you can use "o conf init" to reset your cpan configuration to defaults ):
cpan_home ( example: /home/user/.cpan )
build_dir ( example: /home/user/.cpan/build_dir )
histfile ( example: /home/user/.cpan/histfile )
keep_source_where ( example: /home/user/.cpan/sources )
prefs_dir ( example: /home/user/.cpan/prefs )

**Comment by Levelleor** [comment]
Hey, thank you!

Where do I set those configs? 
I think I solved the issue by just defining $HOME environment variable properly, but I would still love to know where those could be set up.

**Comment by Levelleor** [comment]
Ok I got it, it's a MyConfig.pm file. 

Got it working, tywm :)
